### ISSUE TITLE
C'est pas organiser !

### ISSUE THREAD

**Issue by fcarisey** [tombaud/TP-1-Les-SI#1]
Tu veut pas organiser ton projet, c'est le borel !!! (ouais le borel y'a quoi)

Après je dis ça je dis rien.

**Comment by tombaud** [comment]
Tu veux quoi

**Comment by fcarisey** [comment]
**un beau projet**

**Comment by tombaud** [comment]
Tu n'a pas a me parler comme ca

**Comment by fcarisey** [comment]
- un beau code
- un projet organiser
- des class serais pas de refus

**Comment by fcarisey** [comment]
é lortografe
